### ISSUE TITLE
Mimic --forever option of etcdctl watch

### ISSUE THREAD

**Issue by andrewrynhard** [jimmycuadra/rust-etcd#12]
Is it possible to watch forever?

**Comment by jimmycuadra** [comment]
Something other than what watching in a loop would do? Here's an example of a program that watches a key for changes forever: https://github.com/InQuicker/kaws/blob/95eacc0c0209996c2ac297357ef820defa428abb/agent/src/agent.rs#L43

**Comment by andrewrynhard** [comment]
Ahh. Yes it was just my misunderstanding of the watch method. Didn't realize it blocks.
