### ISSUE TITLE
Support for managing users, roles

### ISSUE THREAD

**Issue by commandline** [jimmycuadra/rust-etcd#19]
I am building some tooling to not only added keys and directories but also users, roles and grants. This doesn't seem possible with this crate. If I'm wrong, a pointer to how these types of entries can be written as plain nodes would be helpful. Otherwise, an additional module or set of modules to support working these types of data in a cluster would be fantastic.

**Comment by commandline** [comment]
https://coreos.com/etcd/docs/latest/v2/auth_api.html

Seems like since for my use I have to use `Client::custom` for now I can execute a few requests with the hyper `Client` instance. Regardless, it would be nice to have the auth API included, especially since the members API is already included.

**Comment by jimmycuadra** [comment]
You're not missing anything—the auth API just hasn't been implemented yet. It's mentioned in the crate docs, but not in the README. Sorry that wasn't more clear!

**Comment by commandline** [comment]
Thanks for clarifying. I have something workable, for now, as I mentioned, and will wait to see this implement in due course. Thanks again for this fantastic crate--I am just now catching up with the hyper 0.11 changes. Thankfully I had done some work with the tokio based version in another project so everything here feels pretty comfortable and idiomatic to tokio and futures.

**Comment by jimmycuadra** [comment]
I finished implementing the auth API a week ago, but still need to flesh out the docs and examples before I publish another version to crates.io. If you want to use the Git master now, you'll be fine. There won't be any more changes to the public API before the release.

**Comment by commandline** [comment]
Excellent, thank you! I will update my dep to point to master, tomorrow, and start re-working my hyper based REST calls to use your API instead.

**Comment by commandline** [comment]
Works well for me--I await the new version to hit crates.io and the updated docs.

Thanks again!
