### ISSUE TITLE
etcd 2.2

### ISSUE THREAD

**Issue by bmartynov** [jimmycuadra/rust-etcd#6]
Hi.
Do you support etсd 2.2?

On etcd 2.2 i have error:
panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(SyntaxError("trailing characters", 1, 5))', ../src/libcore/result.rs:688

let client = Client::default();
let r = client.get("some_key", true, true);

etcd version - 2.2.3.

**Comment by jimmycuadra** [comment]
I haven't worked on this project for a while so it was last tested against etcd 2.1.2. I will be getting everything up to date, though perhaps not very soon. If you want to dig in, a pull request to fix any issues with etcd 2.2 would be greatly appreciated.

**Comment by jimmycuadra** [comment]
I just updated the project and ran the test suite against etcd 2.2.4 and Rust 1.6. Can you try against the master branch and see if the error you got is solved?

**Comment by bmartynov** [comment]
@jimmycuadra Hi.
Yes thank you. Everything is working.
