### ISSUE TITLE
Any way to cancel watch?

### ISSUE THREAD

**Issue by arthurprs** [jimmycuadra/rust-etcd#9]
Is there any way to cancel a watch? Even a simple Client wide close would be really useful.

**Comment by jimmycuadra** [comment]
Right now it blocks until a change happens or until there is a network error of some sort. Being able to cancel it early seems like a good idea. What sort of API do you imagine for it? In the meantime, you could run the watch inside a thread and kill the thread if you need to cancel the watch early.

**Comment by arthurprs** [comment]
The problem is that Rust doesn't provide any reasonable way to kill a thread right now (and probably never will). At least as far as I know.

I checked hyper and I couldn't see any support for canceling either so I ran out of ideas.

**Comment by jmlMetaswitch** [comment]
A time-out and/or a non-blocking method would be a good start (like mpsc). I assume Hyper supports this. 

I see you've been asking about time-outs in https://github.com/hyperium/hyper/issues/417, but it appears that client.set_read_timeout() has been added now (https://hyper.rs/hyper/0.8.0/hyper/client/struct.Client.html).

I'm guessing that HTTP makes a non-blocking method harder.

Would you consider adding a time-out for watches, so that we can then intermittently check whether to terminate in watch threads?

**Comment by jimmycuadra** [comment]
I'm working on updating this crate to user hyper 0.11, which uses an async model based on futures and tokio. You can cancel a future by simply dropping it (letting it go out of scope). I'll see how this plays out for a watch cancellation API as I get further into it.

**Comment by jmlMetaswitch** [comment]
Just so you know, I fully support you spending your free time on this issue, @jimmycuadra! Thank you :-)

I don't suppose you have an idea when this work might be available, do you?

**Comment by jimmycuadra** [comment]
No ETA, but I'll try to make some more progress on this soon!

**Comment by jimmycuadra** [comment]
I worked on it a bit tonight but it's pretty tough and progress is slow. If you'd like to see what I have so far, take a look at the "async" branch.

**Comment by jmlMetaswitch** [comment]
Thanks. I'll probably have to read up on hyper first, but that wouldn't be a bad thing!

**Comment by jimmycuadra** [comment]
Update: Made lots of progress. The next version of the crate is largely done. I still need to update the tests to use the new async functions and improve some docs. Then I will take a look at the watch function and make sure there's a good way to cancel the watch.

**Comment by jmlMetaswitch** [comment]
Great. Really appreciate your work on this.

**Comment by jmlMetaswitch** [comment]
This looks great. Thanks. Are you planning to move up to a new release soon, or are you planning to get more features in first?

**Comment by jimmycuadra** [comment]
I'm gonna add the members and auth API and then make a new release.
